Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./views/blog_views/blog_view.py", line 70, in seearch
    context = search_libs(page, content)
  File "./libs/blog/search_libs.py", line 19, in search_libs
    articles, total = Article.search(content, page, per_page=5)
  File "./libs/search_libs/searchmixin.py", line 23, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "./libs/search_libs/search.py", line 60, in query_index
    'size': per_page
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 655, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ubuntu/.virtualenvs/flask_env3/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'no [query] registered for [multi_math]')